### PR TITLE
component not found message

### PR DESCRIPTION
**Pull request by ayusharma**
ref #17 

Adding a screenshot : 
screen shot 2016-04-06 at 6 46 00 am

I have also made check for the response which produce the following error. Now we are not paring the object which is related to no module found.

```
angular.min.js:92 TypeError: Cannot read property 'toLowerCase' of undefined
    at preProcessComponent (angular.js:1)
    at angular.js:1
    at angular.min.js:72
    at L (angular.min.js:99)
    at L (angular.min.js:99)
    at angular.min.js:101
    at k.$eval (angular.min.js:111)
    at k.$digest (angular.min.js:108)
    at k.$apply (angular.min.js:112)
    at h (angular.min.js:72)
```

note: For development I have disabled html5mode. # is indicating that in url.

### CODE REVIEW

**Comment by wilzbach** [comment]
You have a typo in the error msg - component ;-)

> note: For development I have disabled html5mode. # is indicating that in url.

why?

**Comment by ayusharma** [comment]
@greenify  I did it locally for myself. but did not push that changes of html5mode. I thought a note would be helpful to explain # in url because I am running the application on python -m SimpleHTTPServer and it catches the 404 error in another way. :P

**Comment by wilzbach** [comment]
> I am running the application on python -m SimpleHTTPServer

Use `http-server` (`npm i -g http-server`) ;-)

**Comment by ayusharma** [comment]
Thanks.. It is working fine on http-server too.  :)

**Comment by wilzbach** [comment]
You don't need to disable html5mode there ;-)

**Comment by ayusharma** [comment]
yes, I have enabled html5mode and pull request has the html5mode = enabled ie. `$locationProvider.html5Mode(true);`

**Pull request merged**
